server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/peloton
    username: postgres
    password: futureiscoming
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true


  thymeleaf:
    enabled: true
    encoding: UTF-8